### ISSUE TITLE
Cannot take off on Windows

### ISSUE THREAD

**Issue by delhoume** [remileonard/oldflight#1]
Hi, 

That's a great project (it reminds me playing flight on an Indigo a long long time ago) !

I have compiled your code (except comm.c) with freeglut on Windows 64 and it seems to run well, but I cannot take off, the mouse behaviour seems erratic. I can change direction onleft and right click (but it acts weird) , and cannot position myself of the runway for takeoff...

Are you aware of this ? 
![image](https://user-images.githubusercontent.com/1763447/175939830-536e323b-e899-46ef-9650-33f14c46f3d0.png)

**Comment by remileonard** [comment]
sorry, i removed the glut timer when i compiled the source and test the simulator with my old SGI VWS 320. I restored the timer, the FPS and physic will be much stable.

To be able to take off, a simple solution is to set the flaps to 50 (press "f" 5 times) with the f18, and full power and use the taxi way as the run way, you should be able to rotate at 150 knots, when your in the air, set the flaps to 0 ( capital "F") and gear up ("l")

If you want to taxi on the runway, set the thrust high enough to start moving, do not go any faster than 20 knots, use the right mouse button to turn right and the middle one reset the rudder to the center. If you go to fast, the rudder will stop steering the plane.

I hop it will help you.

**Comment by delhoume** [comment]
Thanks, I have been able to take off, but not on the runway...
I saw some changes from this version on your youtube video :-)

**Comment by delhoume** [comment]
Are you aware of the original port by Michael Gold ? https://notwood.net/sgiflight/
It runs on my Windows 10 machine with some issues (I cannot takeoff because thrust does not move the plane)

**Comment by remileonard** [comment]
yes, i am aware, i've played with it a lot in the days, but because of this issue (tied to the framerate, if you force with your drivers a refresh rate of 30 hz it will work) i start this port :)

**Comment by remileonard** [comment]
> Thanks, I have been able to take off, but not on the runway... I saw some changes from this version on your youtube video :-)

the youtube video is done with somes assets from strike commander loaded with librealspace, you can play with it, it is on the branche strike_commander (press s to fly in a strike commander map)

**Comment by delhoume** [comment]
Thanks for your answers
